---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
    - port: 443
  selector:
    app: app
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  serviceName: app-service
  template:
    metadata:
      labels:
        app: myapp
        role: unset
    spec:
      containers:
      - name: webapp
        image: webapp:local
        command: [ sleep, infinity ]
