---
apiVersion: v1
kind: Service
metadata:
  name: conjur-follower
  labels:
    app: conjur-follower
spec:
  ports:
  - port: 443
    name: https
  - port: 636
    name: ldaps
  selector:
    app: conjur-follower
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: conjur-follower
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: conjur-follower
        role: follower
    spec:
      containers:
      - name: conjur-follower
        image: conjur-appliance:local
        ports:
        - containerPort: 443
          name: https
        - containerPort: 5432
          name: pg-main
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "trap : TERM INT; sleep infinity & wait" ]
