---
apiVersion: v1
kind: Service
metadata:
  name: conjur-stateful-subcluster
spec:
  ports:
  - port: 443
  clusterIP: None
  selector:
    app: conjur-node
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: conjur-stateful-node
spec:
  serviceName: conjur-stateful-subcluster
  replicas: 3
  template:
    metadata:
      labels:
        app: conjur-node
        role: unset        # set to master or standby when configured
    spec:
      containers:
      - name: conjur-appliance
        image: conjur-appliance:local
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
