---
apiVersion: v1
kind: Service
metadata:
  name: conjur-master
  labels:
    app: conjur-node
spec:
  ports:
  - port: 443
    name: https
  - port: 636
    name: ldaps
  - port: 5432
    name: pg-main
  - port: 5433
    name: pg-audit
  selector:
    app: conjur-master
  type: LoadBalancer	# forces creation of NodePort for external access
---
apiVersion: v1
kind: Pod
metadata:
metadata:
  name: conjur-master
  labels:
    app: conjur-node
    role: master
spec:
  containers:
  - name: conjur-appliance
    image: conjur-appliance:local
    ports:
    - containerPort: 443
      name: https
    - containerPort: 636
      name: ldaps
    - containerPort: 5432
      name: pg-main
    - containerPort: 5433
      name: pg-audit
