apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: conjur-appliance
  name: conjur-node
  namespace: conjur
spec:
  template:
    metadata:
      labels:
        app: conjur-appliance
        role: unset        # set to master or standby when configured
    spec:
      containers:
      - name: conjur-appliance
        image: conjur-appliance:local
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
