---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-dev
spec:
  containers:
  - name: webapp
    image: webapp:local
    command: [ sleep, infinity ]
    env:
    - name: CONJUR_APPLIANCE_URL
      value: https://conjur-follower.conjur.svc.cluster.local/api
    - name: CONJUR_AUTHN_URL
      value: https://conjur-follower.conjur.svc.cluster.local/api/authn-k8s/minikube
    - name: CONJUR_ACCOUNT
      value: dev
    - name: CONJUR_AUTHN_LOGIN
      value: webapp/pod/webapp
    - name: CONJUR_MAJOR_VERSION
      value: "4"
    - name: CONJUR_SSL_CERTIFICATE
      valueFrom:
        configMapKeyRef:
          name: webapp
          key: ssl_certificate
